### ISSUE TITLE
Issues with unpacking

### ISSUE THREAD

**Issue by JohnMackYouTube05** [panzi/u4pak#25]
I'm trying to unpack Astroneer, the Windows store version. I have already found the files and copied them to the appropriate location, but when I try to unpack the pak file it throws up this error: `C:\Users\liljm\Downloads\u4pak-master\u4pak-master>u4pak.py unpack "C:\Users\liljm\Downloads\u4pak-master\SystemEraSoftworks.29415440E1269_1.2.10.0_x64__ftk5pbg2rayv2\Astro\Content\Paks\Astro-UWP64.pak"
illegal file magic: 0x2ce7133f` But when I run the unpack command on the folder of the game itself instead of just the pak file, it throws up this error instead: `u4pak-master>u4pak.py unpack "C:\Users\liljm\Downloads\u4pak-master\SystemEraSoftworks.29415440E1269_1.2.10.0_x64__ftk5pbg2rayv2"
[Errno 13] Permission denied: 'C:\\Users\\liljm\\Downloads\\u4pak-master\\SystemEraSoftworks.29415440E1269_1.2.10.0_x64__ftk5pbg2rayv2` It says access denied. I tried running Windows Command Prompt as administrator too, and it still says access denied. Please someone explain to me why this is happening! I want to access Astroneer game files for private non-commerical personal use!

Error Picture: 
![image](https://user-images.githubusercontent.com/16242045/60385155-be73de00-9a4b-11e9-9ac6-1a73493e8bc1.png)

**Comment by panzi** [comment]
`illegal file magic` means that whatever file format that file is, my script does not recognize it. Probably not an Unreal Engine 4 archive file, or somehow obfuscated so that my script can't read it. Sorry.

You get `Permission denied` when running it on a folder because it is expecting a file and when you try to open a folder like a file I suppose you get a permission error under Windows? I don't use Windows. In any case it is not meant to be run on a folder.
