### ISSUE TITLE
u4pak runs on command prompt, but does nothing when i use pack/unpack commands

### ISSUE THREAD

**Issue by ntnhan241** [panzi/u4pak#46]
I install u4pak for the first time today, with Python version 3.7.3.
I ran u4pak using command prompt (even try with Administrator privilege). When i try unpack command, the cmd prompt does nothing, no bug, no warning, just nothing. I tried updating the Python with the lastest version (3.9.5), still nothing happens, same with the pack command.

**Comment by panzi** [comment]
Can you show me the exact output? How exactly do you run it exactly? E.g. when running it with `--help` it should look somewhat like this:
```
panzi@panzi u4pak [master*]$ python3 ./u4pak.py --help
usage: u4pak.py [-h] command ...

unpack, list and mount Unreal Engine 4 .pak archives

positional arguments:
  command
    unpack (x)
              unpack archive
    pack (c)  pack archive
    list (l)  list archive contens
    info (i)  print archive summary info
    test (t)  test archive integrity
    mount (m)
              fuse mount archive

optional arguments:
  -h, --help  show this help message and exit
panzi@panzi u4pak [master*]$ 
```
No I guess you use Windows instead of Linux, but it should be quite similar there, too. Start python.exe with the path to the script as parameter and then followed by the parameters to the script.

(Btw. I'm working on a re-implementation of this script in Rust that will have a native binary for Windows that won't require Python and that might be faster. Will still be a CLI tool, because CLI tools are more flexible, can be used in an automated workflow, and I definitely won't do any Windows GUI work. For programmers CLI tools are more handy anyway.)

**Comment by agc93** [comment]
@panzi I've been helping @ntnhan241 with this over the last hour or so and  turns out it was working fine, just a user/env issue

**Comment by ntnhan241** [comment]
Problem solved thank you very much for answering, much appreciated. Apparently I need to change my directory of my command prompt first.
