### ISSUE TITLE
u4pack wont work

### ISSUE THREAD

**Issue by Tanron009** [panzi/u4pak#65]
Hi, i get this error with u4pack

"Invalid number of parameters
[Errno 2] No such file or directory: 'FortniteGame'
The system cannot find the file specified.

[Errno 22] Invalid argument

[Errno 22] Invalid argument

[Errno 22] Invalid argument

"C:\Users\tanor\OneDrive\Skjöl\Unreal Projects\hehe\Saved\Cooked\WindowsNoEditor\hehe\Content\FortniteGame\FortniteGame" -> 'pak\FortniteGame.pak'

Press any key to quit."

Any way to fix it??

https://github.com/panzi/u4pak/assets/117080892/a58e9179-11e8-46e9-adb3-ca0e3a55b6dd

**Comment by panzi** [comment]
I don't know that the .bat file is that you're using. It seems it passes wrong arguments to the Python script. So that would need to be fixed by whoever wrote that .bat file. Also there is now this IMO better version of u4pak: https://github.com/panzi/rust-u4pak Maybe that will work better? It's not a drop-in replacement, though, meaning it has some other arguments.

Also note: I don't use Windows and don't have Fortnite, so I don't know if that can even be handled by my script.

**Comment by Tanron009** [comment]
Im kinda stupid so i have no clue how to use rust u4pak and there are no tutorials out there. what do i do after i open the exe?? (i want to pak the uasset)

**Comment by panzi** [comment]
Write a .u4pak file as described in the readme and drop that on the exe or associate that extension with the exe so you can just double click it. But in any case I'd recommend to learn how to use and automate things with the shell (command prompt/cmd.exe/Power She'll?). If you want to do anything like software development (game modding is that, IMO), knowing how to actually run programs and automate stuff is very useful. I don't use Windows, so I can't tell you more about this. You can compile programs for Windows under Linux, so I never even touched Windows to create the exe.

**Comment by Tanron009** [comment]
im too retarded for this stuff, if you could make a video or something on how to do this itll be great. I highly doubt you will do it but if you do make sure your making a uasset into a pak

**Comment by panzi** [comment]
Sorry, I can't make a video on how to do this on Windows because I use Linux. And I'm not sure if I even have any Unreal Engine 4 game installed at the moment. But with a quick search I found this playlist about how to use the Windows command line: https://www.youtube.com/watch?v=MBBWVgE0ewk&list=PL6gx4Cwl9DGDV6SnbINlVUd0o2xT4JbMu
Scanning over it, 1-5 are the very basics, 6 and 7 aren't that relevant here, 8 and 9 are some more "advanced" handy things (or basics part 2). And anything you type in there you can also just put in a text file with the extension .bat and execute that like a program. (If you run it via double clicking put `pause` at the end of the file to keep the window open after execution so that you can see the output.) Always think of the double quotes is there potentially are spaces in a file path!

In any case, double clicking u4pak.exe does nothing. You need to pass something to it. Put it into e.g. `C:\Windows\System32`, then open `cmd.exe` and type `u4pak help` or `u4pak help pack`. You can pack things with:
```
u4pak pack Output.pak "Some\Input\Folder"
```

You might need to specify a `--mount-point`:

```
u4pak pack --mount-point some/path Output.pak "Some\Input\Folder"
```

IIRC you can get that from the existing old archive with:

```
u4pak info Original.pak
```

I didn't actually use it myself to mod a game, only to extract things to look at/listen to outside of the game. Just out of curiosity.

**Comment by Tanron009** [comment]
Alright, thank you!
